<a href="https://colab.research.google.com/github/CarineIradukunda/PyTorch-AI-database-protection-/blob/master/prvateAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([0, 1, 1,  ..., 1, 0, 0], dtype=torch.uint8)

In [0]:
db.shape

torch.Size([5000])

In [0]:
db[0:5]

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

In [0]:
remove_index=2

In [0]:
def get_parallel_db(db,remove_index):
  return torch.cat((db[0:remove_index],db[remove_index+1:])) 


In [0]:
get_parallel_db(db,5000)


tensor([0, 1, 1,  ..., 1, 0, 0], dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  
  parallel_dbs=list()
  
  for i in range(len(db)):
    
    pdb=get_parallel_db(db,i)
    parallel_dbs.append(pdb)
  
  return parallel_dbs


In [0]:
pdbs=get_parallel_dbs(db)

In [0]:
def create_db_parallels(num_entries):
  
  db=torch.rand(num_entries)>0.5
  pdbs=get_parallel_dbs(db)
  
  return db,pdbs
  

In [0]:
db,pdbs=create_db_parallels(20)
db

tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
       dtype=torch.uint8)

In [0]:
pdbs

[tensor([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [0]:
def query(db):
  return db.sum()

In [0]:
full_db_result=query(db)

In [0]:
max_distance=0
for pdb in pdbs:
  pdb_result=query(pdb)
  
  db_distance=torch.abs(pdb_result-full_db_result)
  
  if(db_distance > max_distance):
    max_distance = db_distance
  

In [0]:
max_distance#the database is made of 0,1.the maximum sum we can get is 1.

tensor(1)

In [0]:

def sensitivity(query,n_entries=1000):
  db,pdbs = create_db_parallels(n_entries)
  full_db_results = query(db)
  
  max_distance=0
  for pdb in pdbs:
    
    pdb_result=query(pdb)
  
    db_distance=torch.abs(pdb_result-full_db_result)
  
    if(db_distance > max_distance):
      max_distance = db_distance
      
  return max_distance


In [0]:
def query(db):
  return db.sum()

In [0]:
sensitivity(query)

tensor(480)

In [0]:
def query(db,threshold=5):
  return (db.sum()>threshold).float()

In [0]:
for i in range(10):
  sens_f=sensitivity(query, n_entries=10)
  print(sens_f)

tensor(13.)
tensor(14.)
tensor(14.)
tensor(14.)
tensor(14.)
tensor(13.)
tensor(14.)
tensor(14.)
tensor(14.)
tensor(14.)


In [0]:
db,_=create_db_parallels(100)
db

tensor([0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        0, 1, 0, 0], dtype=torch.uint8)

In [0]:
pdb=get_parallel_db(db,remove_index=10)


In [0]:
db[10]

tensor(0, dtype=torch.uint8)

In [0]:
#differencing attack using sum query
sum(db)-sum(pdb)

tensor(0, dtype=torch.uint8)

In [0]:
#differencing attack using mean query
(sum(db).float()/len(db))-(sum(pdb).float()/len(pdb))

tensor(-0.0041)

In [0]:
#differencing attack using a treshold

(sum(db).float()>49)-(sum(pdb).float() >49)

tensor(0, dtype=torch.uint8)

In [0]:
db,pdbs=create_db_parallels(100)

In [0]:
db

tensor([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
        1, 0, 1, 1], dtype=torch.uint8)

In [0]:
#def query(db,noise=0.2):
  noise=0.2
  true_result=torch.mean(db.float())
  
  first_coin_flip=(torch.rand(len(db)) > noise).float()
  second_coin_flip=(torch.rand(len(db)) > 0.5).float()

  augmented_database=db.float() * first_coin_flip + (1-first_coin_flip)* second_coin_flip

  sk_result=torch.mean(augmented_database.float()) * 2 - 0.5#making the db having the same average as the original one:true_result
  
  #return db_result, true_result

In [0]:
 sk_result
  

tensor(0.5200)

In [0]:
db,pdbs=create_db_parallels(100)
private_result,true_result=query(db)
print("with noise:"+str(private_result))
print("without noise:"+str(true_result))

with noise:tensor(0.4800)
without noise:tensor(0.5300)


In [0]:
first_coin_flip

tensor([1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1.,
        0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0.,
        1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1.,
        0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
        1., 1., 0., 1., 1., 1., 1., 0., 1., 0.])

In [0]:
second_coin_flip

tensor([1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1.,
        0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1.,
        0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1.,
        1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1.,
        1., 1., 0., 1., 0., 0., 1., 0., 0., 1.])

In [0]:
db.float() * first_coin_flip

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
        1., 1., 0., 1., 0., 0., 1., 0., 1., 0.])

In [0]:
(1-first_coin_flip)

tensor([0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
        0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
        1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
        1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 1.])

In [0]:
true_result=torch.mean(db.float())
true_result

tensor(0.4500)

In [0]:
#generating differentially private labels for a dataset
import numpy as np

In [0]:
num_teachers=10 #10 partner hpspitals
num_examples=10000 #size of our dataset
num_labels=10 #number of labels for our classifier

In [0]:
preds=(np.random.rand(num_teachers,num_examples) * num_labels).astype(int)#fake predictions

In [0]:
preds

array([[6, 6, 4, ..., 0, 1, 7],
       [2, 5, 2, ..., 3, 3, 6],
       [3, 4, 9, ..., 2, 9, 4],
       ...,
       [1, 1, 2, ..., 0, 1, 3],
       [8, 5, 9, ..., 8, 8, 8],
       [8, 2, 8, ..., 7, 6, 8]])

In [0]:
an_image = preds[1,0]

In [0]:
label_counts=np.bincount(an_image,)